# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userNickname', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=100)),
                ('userIPAdress', models.CharField(max_length=15)),
            ],
        ),
    ]
